apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: feekzk8s-com-tls
spec:
  secretName: feekzk8s-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: feekzk8s.com
  dnsNames:
    - feekzk8s.com
    - www.feekzk8s.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - feekzk8s.com
          - www.feekzk8s.com
      




